/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated.financeiro'
import { Route as AuthenticatedExpedicaoRouteImport } from './routes/_authenticated.expedicao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated.comercial'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated.cliente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated.financeiro.index'
import { Route as AuthenticatedExpedicaoIndexRouteImport } from './routes/_authenticated.expedicao.index'
import { Route as AuthenticatedComercialIndexRouteImport } from './routes/_authenticated.comercial.index'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated.cliente.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedFinanceiroReceberRouteImport } from './routes/_authenticated.financeiro.receber'
import { Route as AuthenticatedFinanceiroPagarRouteImport } from './routes/_authenticated.financeiro.pagar'
import { Route as AuthenticatedFinanceiroFornecedoresRouteImport } from './routes/_authenticated.financeiro.fornecedores'
import { Route as AuthenticatedFinanceiroCentrosCustoRouteImport } from './routes/_authenticated.financeiro.centros-custo'
import { Route as AuthenticatedFinanceiroBancosRouteImport } from './routes/_authenticated.financeiro.bancos'
import { Route as AuthenticatedExpedicaoEstoqueRouteImport } from './routes/_authenticated.expedicao.estoque'
import { Route as AuthenticatedExpedicaoEntregasRouteImport } from './routes/_authenticated.expedicao.entregas'
import { Route as AuthenticatedComercialProdutosRouteImport } from './routes/_authenticated.comercial.produtos'
import { Route as AuthenticatedComercialPedidosRouteImport } from './routes/_authenticated.comercial.pedidos'
import { Route as AuthenticatedComercialClientesRouteImport } from './routes/_authenticated.comercial.clientes'
import { Route as AuthenticatedClientePedidosRouteImport } from './routes/_authenticated.cliente.pedidos'
import { Route as AuthenticatedClienteCashbackRouteImport } from './routes/_authenticated.cliente.cashback'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated.admin.relatorios'
import { Route as AuthenticatedAdminFuncionariosRouteImport } from './routes/_authenticated.admin.funcionarios'
import { Route as AuthenticatedAdminEmpresaRouteImport } from './routes/_authenticated.admin.empresa'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated.admin.audit-logs'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpedicaoRoute = AuthenticatedExpedicaoRouteImport.update({
  id: '/expedicao',
  path: '/expedicao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedExpedicaoIndexRoute =
  AuthenticatedExpedicaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpedicaoRoute,
  } as any)
const AuthenticatedComercialIndexRoute =
  AuthenticatedComercialIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedFinanceiroReceberRoute =
  AuthenticatedFinanceiroReceberRouteImport.update({
    id: '/receber',
    path: '/receber',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroPagarRoute =
  AuthenticatedFinanceiroPagarRouteImport.update({
    id: '/pagar',
    path: '/pagar',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroFornecedoresRoute =
  AuthenticatedFinanceiroFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroCentrosCustoRoute =
  AuthenticatedFinanceiroCentrosCustoRouteImport.update({
    id: '/centros-custo',
    path: '/centros-custo',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroBancosRoute =
  AuthenticatedFinanceiroBancosRouteImport.update({
    id: '/bancos',
    path: '/bancos',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedExpedicaoEstoqueRoute =
  AuthenticatedExpedicaoEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedExpedicaoRoute,
  } as any)
const AuthenticatedExpedicaoEntregasRoute =
  AuthenticatedExpedicaoEntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => AuthenticatedExpedicaoRoute,
  } as any)
const AuthenticatedComercialProdutosRoute =
  AuthenticatedComercialProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedComercialPedidosRoute =
  AuthenticatedComercialPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedComercialClientesRoute =
  AuthenticatedComercialClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedComercialRoute,
  } as any)
const AuthenticatedClientePedidosRoute =
  AuthenticatedClientePedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedClienteCashbackRoute =
  AuthenticatedClienteCashbackRouteImport.update({
    id: '/cashback',
    path: '/cashback',
    getParentRoute: () => AuthenticatedClienteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFuncionariosRoute =
  AuthenticatedAdminFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresaRoute =
  AuthenticatedAdminEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/comercial': typeof AuthenticatedComercialRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expedicao': typeof AuthenticatedExpedicaoRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/empresa': typeof AuthenticatedAdminEmpresaRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/cashback': typeof AuthenticatedClienteCashbackRoute
  '/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/comercial/clientes': typeof AuthenticatedComercialClientesRoute
  '/comercial/pedidos': typeof AuthenticatedComercialPedidosRoute
  '/comercial/produtos': typeof AuthenticatedComercialProdutosRoute
  '/expedicao/entregas': typeof AuthenticatedExpedicaoEntregasRoute
  '/expedicao/estoque': typeof AuthenticatedExpedicaoEstoqueRoute
  '/financeiro/bancos': typeof AuthenticatedFinanceiroBancosRoute
  '/financeiro/centros-custo': typeof AuthenticatedFinanceiroCentrosCustoRoute
  '/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/comercial/': typeof AuthenticatedComercialIndexRoute
  '/expedicao/': typeof AuthenticatedExpedicaoIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/empresa': typeof AuthenticatedAdminEmpresaRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/cashback': typeof AuthenticatedClienteCashbackRoute
  '/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/comercial/clientes': typeof AuthenticatedComercialClientesRoute
  '/comercial/pedidos': typeof AuthenticatedComercialPedidosRoute
  '/comercial/produtos': typeof AuthenticatedComercialProdutosRoute
  '/expedicao/entregas': typeof AuthenticatedExpedicaoEntregasRoute
  '/expedicao/estoque': typeof AuthenticatedExpedicaoEstoqueRoute
  '/financeiro/bancos': typeof AuthenticatedFinanceiroBancosRoute
  '/financeiro/centros-custo': typeof AuthenticatedFinanceiroCentrosCustoRoute
  '/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/comercial': typeof AuthenticatedComercialIndexRoute
  '/expedicao': typeof AuthenticatedExpedicaoIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRouteWithChildren
  '/_authenticated/comercial': typeof AuthenticatedComercialRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expedicao': typeof AuthenticatedExpedicaoRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/empresa': typeof AuthenticatedAdminEmpresaRoute
  '/_authenticated/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/cliente/cashback': typeof AuthenticatedClienteCashbackRoute
  '/_authenticated/cliente/pedidos': typeof AuthenticatedClientePedidosRoute
  '/_authenticated/comercial/clientes': typeof AuthenticatedComercialClientesRoute
  '/_authenticated/comercial/pedidos': typeof AuthenticatedComercialPedidosRoute
  '/_authenticated/comercial/produtos': typeof AuthenticatedComercialProdutosRoute
  '/_authenticated/expedicao/entregas': typeof AuthenticatedExpedicaoEntregasRoute
  '/_authenticated/expedicao/estoque': typeof AuthenticatedExpedicaoEstoqueRoute
  '/_authenticated/financeiro/bancos': typeof AuthenticatedFinanceiroBancosRoute
  '/_authenticated/financeiro/centros-custo': typeof AuthenticatedFinanceiroCentrosCustoRoute
  '/_authenticated/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresRoute
  '/_authenticated/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/_authenticated/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_authenticated/comercial/': typeof AuthenticatedComercialIndexRoute
  '/_authenticated/expedicao/': typeof AuthenticatedExpedicaoIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/admin'
    | '/cliente'
    | '/comercial'
    | '/dashboard'
    | '/expedicao'
    | '/financeiro'
    | '/admin/audit-logs'
    | '/admin/empresa'
    | '/admin/funcionarios'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/cliente/cashback'
    | '/cliente/pedidos'
    | '/comercial/clientes'
    | '/comercial/pedidos'
    | '/comercial/produtos'
    | '/expedicao/entregas'
    | '/expedicao/estoque'
    | '/financeiro/bancos'
    | '/financeiro/centros-custo'
    | '/financeiro/fornecedores'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/admin/'
    | '/cliente/'
    | '/comercial/'
    | '/expedicao/'
    | '/financeiro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/dashboard'
    | '/admin/audit-logs'
    | '/admin/empresa'
    | '/admin/funcionarios'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/cliente/cashback'
    | '/cliente/pedidos'
    | '/comercial/clientes'
    | '/comercial/pedidos'
    | '/comercial/produtos'
    | '/expedicao/entregas'
    | '/expedicao/estoque'
    | '/financeiro/bancos'
    | '/financeiro/centros-custo'
    | '/financeiro/fornecedores'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/admin'
    | '/cliente'
    | '/comercial'
    | '/expedicao'
    | '/financeiro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/cliente'
    | '/_authenticated/comercial'
    | '/_authenticated/dashboard'
    | '/_authenticated/expedicao'
    | '/_authenticated/financeiro'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/empresa'
    | '/_authenticated/admin/funcionarios'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/cliente/cashback'
    | '/_authenticated/cliente/pedidos'
    | '/_authenticated/comercial/clientes'
    | '/_authenticated/comercial/pedidos'
    | '/_authenticated/comercial/produtos'
    | '/_authenticated/expedicao/entregas'
    | '/_authenticated/expedicao/estoque'
    | '/_authenticated/financeiro/bancos'
    | '/_authenticated/financeiro/centros-custo'
    | '/_authenticated/financeiro/fornecedores'
    | '/_authenticated/financeiro/pagar'
    | '/_authenticated/financeiro/receber'
    | '/_authenticated/admin/'
    | '/_authenticated/cliente/'
    | '/_authenticated/comercial/'
    | '/_authenticated/expedicao/'
    | '/_authenticated/financeiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expedicao': {
      id: '/_authenticated/expedicao'
      path: '/expedicao'
      fullPath: '/expedicao'
      preLoaderRoute: typeof AuthenticatedExpedicaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/expedicao/': {
      id: '/_authenticated/expedicao/'
      path: '/'
      fullPath: '/expedicao/'
      preLoaderRoute: typeof AuthenticatedExpedicaoIndexRouteImport
      parentRoute: typeof AuthenticatedExpedicaoRoute
    }
    '/_authenticated/comercial/': {
      id: '/_authenticated/comercial/'
      path: '/'
      fullPath: '/comercial/'
      preLoaderRoute: typeof AuthenticatedComercialIndexRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/financeiro/receber': {
      id: '/_authenticated/financeiro/receber'
      path: '/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroReceberRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/pagar': {
      id: '/_authenticated/financeiro/pagar'
      path: '/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagarRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/fornecedores': {
      id: '/_authenticated/financeiro/fornecedores'
      path: '/fornecedores'
      fullPath: '/financeiro/fornecedores'
      preLoaderRoute: typeof AuthenticatedFinanceiroFornecedoresRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/centros-custo': {
      id: '/_authenticated/financeiro/centros-custo'
      path: '/centros-custo'
      fullPath: '/financeiro/centros-custo'
      preLoaderRoute: typeof AuthenticatedFinanceiroCentrosCustoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/bancos': {
      id: '/_authenticated/financeiro/bancos'
      path: '/bancos'
      fullPath: '/financeiro/bancos'
      preLoaderRoute: typeof AuthenticatedFinanceiroBancosRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/expedicao/estoque': {
      id: '/_authenticated/expedicao/estoque'
      path: '/estoque'
      fullPath: '/expedicao/estoque'
      preLoaderRoute: typeof AuthenticatedExpedicaoEstoqueRouteImport
      parentRoute: typeof AuthenticatedExpedicaoRoute
    }
    '/_authenticated/expedicao/entregas': {
      id: '/_authenticated/expedicao/entregas'
      path: '/entregas'
      fullPath: '/expedicao/entregas'
      preLoaderRoute: typeof AuthenticatedExpedicaoEntregasRouteImport
      parentRoute: typeof AuthenticatedExpedicaoRoute
    }
    '/_authenticated/comercial/produtos': {
      id: '/_authenticated/comercial/produtos'
      path: '/produtos'
      fullPath: '/comercial/produtos'
      preLoaderRoute: typeof AuthenticatedComercialProdutosRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/comercial/pedidos': {
      id: '/_authenticated/comercial/pedidos'
      path: '/pedidos'
      fullPath: '/comercial/pedidos'
      preLoaderRoute: typeof AuthenticatedComercialPedidosRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/comercial/clientes': {
      id: '/_authenticated/comercial/clientes'
      path: '/clientes'
      fullPath: '/comercial/clientes'
      preLoaderRoute: typeof AuthenticatedComercialClientesRouteImport
      parentRoute: typeof AuthenticatedComercialRoute
    }
    '/_authenticated/cliente/pedidos': {
      id: '/_authenticated/cliente/pedidos'
      path: '/pedidos'
      fullPath: '/cliente/pedidos'
      preLoaderRoute: typeof AuthenticatedClientePedidosRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/cliente/cashback': {
      id: '/_authenticated/cliente/cashback'
      path: '/cashback'
      fullPath: '/cliente/cashback'
      preLoaderRoute: typeof AuthenticatedClienteCashbackRouteImport
      parentRoute: typeof AuthenticatedClienteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funcionarios': {
      id: '/_authenticated/admin/funcionarios'
      path: '/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AuthenticatedAdminFuncionariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresa': {
      id: '/_authenticated/admin/empresa'
      path: '/empresa'
      fullPath: '/admin/empresa'
      preLoaderRoute: typeof AuthenticatedAdminEmpresaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminEmpresaRoute: typeof AuthenticatedAdminEmpresaRoute
  AuthenticatedAdminFuncionariosRoute: typeof AuthenticatedAdminFuncionariosRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminEmpresaRoute: AuthenticatedAdminEmpresaRoute,
  AuthenticatedAdminFuncionariosRoute: AuthenticatedAdminFuncionariosRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClienteRouteChildren {
  AuthenticatedClienteCashbackRoute: typeof AuthenticatedClienteCashbackRoute
  AuthenticatedClientePedidosRoute: typeof AuthenticatedClientePedidosRoute
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
}

const AuthenticatedClienteRouteChildren: AuthenticatedClienteRouteChildren = {
  AuthenticatedClienteCashbackRoute: AuthenticatedClienteCashbackRoute,
  AuthenticatedClientePedidosRoute: AuthenticatedClientePedidosRoute,
  AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
}

const AuthenticatedClienteRouteWithChildren =
  AuthenticatedClienteRoute._addFileChildren(AuthenticatedClienteRouteChildren)

interface AuthenticatedComercialRouteChildren {
  AuthenticatedComercialClientesRoute: typeof AuthenticatedComercialClientesRoute
  AuthenticatedComercialPedidosRoute: typeof AuthenticatedComercialPedidosRoute
  AuthenticatedComercialProdutosRoute: typeof AuthenticatedComercialProdutosRoute
  AuthenticatedComercialIndexRoute: typeof AuthenticatedComercialIndexRoute
}

const AuthenticatedComercialRouteChildren: AuthenticatedComercialRouteChildren =
  {
    AuthenticatedComercialClientesRoute: AuthenticatedComercialClientesRoute,
    AuthenticatedComercialPedidosRoute: AuthenticatedComercialPedidosRoute,
    AuthenticatedComercialProdutosRoute: AuthenticatedComercialProdutosRoute,
    AuthenticatedComercialIndexRoute: AuthenticatedComercialIndexRoute,
  }

const AuthenticatedComercialRouteWithChildren =
  AuthenticatedComercialRoute._addFileChildren(
    AuthenticatedComercialRouteChildren,
  )

interface AuthenticatedExpedicaoRouteChildren {
  AuthenticatedExpedicaoEntregasRoute: typeof AuthenticatedExpedicaoEntregasRoute
  AuthenticatedExpedicaoEstoqueRoute: typeof AuthenticatedExpedicaoEstoqueRoute
  AuthenticatedExpedicaoIndexRoute: typeof AuthenticatedExpedicaoIndexRoute
}

const AuthenticatedExpedicaoRouteChildren: AuthenticatedExpedicaoRouteChildren =
  {
    AuthenticatedExpedicaoEntregasRoute: AuthenticatedExpedicaoEntregasRoute,
    AuthenticatedExpedicaoEstoqueRoute: AuthenticatedExpedicaoEstoqueRoute,
    AuthenticatedExpedicaoIndexRoute: AuthenticatedExpedicaoIndexRoute,
  }

const AuthenticatedExpedicaoRouteWithChildren =
  AuthenticatedExpedicaoRoute._addFileChildren(
    AuthenticatedExpedicaoRouteChildren,
  )

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroBancosRoute: typeof AuthenticatedFinanceiroBancosRoute
  AuthenticatedFinanceiroCentrosCustoRoute: typeof AuthenticatedFinanceiroCentrosCustoRoute
  AuthenticatedFinanceiroFornecedoresRoute: typeof AuthenticatedFinanceiroFornecedoresRoute
  AuthenticatedFinanceiroPagarRoute: typeof AuthenticatedFinanceiroPagarRoute
  AuthenticatedFinanceiroReceberRoute: typeof AuthenticatedFinanceiroReceberRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroBancosRoute: AuthenticatedFinanceiroBancosRoute,
    AuthenticatedFinanceiroCentrosCustoRoute:
      AuthenticatedFinanceiroCentrosCustoRoute,
    AuthenticatedFinanceiroFornecedoresRoute:
      AuthenticatedFinanceiroFornecedoresRoute,
    AuthenticatedFinanceiroPagarRoute: AuthenticatedFinanceiroPagarRoute,
    AuthenticatedFinanceiroReceberRoute: AuthenticatedFinanceiroReceberRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRouteWithChildren
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpedicaoRoute: typeof AuthenticatedExpedicaoRouteWithChildren
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClienteRoute: AuthenticatedClienteRouteWithChildren,
  AuthenticatedComercialRoute: AuthenticatedComercialRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpedicaoRoute: AuthenticatedExpedicaoRouteWithChildren,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
